### ISSUE TITLE
packet facilities get fails when a facility is not assigned to metro (staff API key)

### ISSUE THREAD

**Issue by jeremytanner** [equinix/metal-cli#118]
### What happened?

When using a staff API key, `packet facilities get` fails. Likely cause is facilities like `sg4` that are only staff viewable that have `"metro": null` as they don't belong to a metro, but facilities requires a metro to build the table.

### How can we reproduce it?

```
% packet facilities get

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x146cbc3]
goroutine 1 [running]:
github.com/packethost/packet-cli/cmd.glob..func32(0x1990020, 0x19c44f0, 0x0, 0x0, 0x0, 0x0)
	/home/runner/work/packet-cli/packet-cli/cmd/retrieve_facilities.go:48 +0x223
github.com/spf13/cobra.(*Command).execute(0x1990020, 0x19c44f0, 0x0, 0x0, 0x1990020, 0x19c44f0)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0x198f840, 0x0, 0x14b69c0, 0xc00008e058)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/home/runner/work/packet-cli/packet-cli/main.go:31 +0x33
```

CLI version (`packet --version`):  packet version 0.4.0

packet-darwin-amd64 binary on macOS 11.3.1

**Comment by displague** [comment]
This looks like a `packet facilities get` bug when entitlements include certain facilities that are not associated with a metro
